# Link documentação de propriedades do Spring: https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties
spring:
#  profiles:
#    active: dev
  main:
    # Habilita a reescrita da definição de beans, quando registrar um bean com um nome existente.
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      # Habilita possibilidade de serialização de beans vazios sem erros
      fail-on-empty-beans: false
    # Habilita inicialização de componentes sob demanada.
    lazy-initialization: true

  # CONFIGURAÇÃO DO DATASOURCE:
  datasource:
    # URL de acesso ao banco de dados.
    url: jdbc:mariadb://localhost:3306/alma?autoReconnect=true&useSSL=false
    # Usuário de conexão com o banco de dados.
    username: alma
    # Senha do usuário de conexão com o banco de dados.
    password: almapwd

  # CONFIGURAÇÃO DO JPA:
  jpa:
    hibernate:
      # Definição do Modo de DDL.
      # Opções:
      # * validate: Apenas VALIDA o schema, NãO realiza nenhuma alteração na base de dados.
      # * update: Realiza a ATUALIZAÇÃO da base de dados seguindo o mapeamento de entidades.
      # * create: CRIA todos os objetos do banco de dados seguindo o mapeamento de entidades, DELETA todos os dados anteriores.
      # * create-drop: Realiza o DROP do schema quando a sessão do SessionFactory é explicitamente fechado, normalmente quando a aplicação é encerrada.
      # * none: NãO realiza nenhuma alteração na base de dados.
      ddl-auto: none
      # Define se deve ser utilizado a nova função de mapeamento e geração de ids
      # Função é apenas um atalho e será desabilitada para permitir a customização da tabela de auditoria
      # o mapeamento e geração de ids ainda pode ser configurado manualmente e individualmente em cada uma das entidades
      use-new-id-generator-mappings: false
      # Necessário ppara respeitar o case sensitive nos nomes da tabela
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Define se as instruções SQL executadas devem ser exibidas no log.
    show-sql: false
    # Define se deve inicializado um schema a partir do arquivo de configuração.
    generate-ddl: false
    # Define o tipo de dialeto do banco de dados. Por padrão é definido para auto  identificar
    database-platform: org.hibernate.dialect.MySQL57Dialect


  # CONFIGURAÇÕES GENÉRICAS
  data:
    rest:
      # URL base da aplicação.
      base-path: /api/alma
#  servlet:
#    # Definições de manipulação de arquivos
#    multipart:
#      # Define tamanho máximo aceito
#      max-file-size: 100MB
#      # Define o tamanho máximo do request
#      max-request-size: 100MB

  # CONFIGURAÇÔES DE CACHE
#  cache:
#    type: ehcache
#  redis:
#    host: localhost
#    redisport: 6379

# CONFIGURAÇÃO DO SERVIDOR (API)
server:
  # Define a porta utilizada pelo servidor do context-path.
  port: 8085
  error:
    include-stacktrace: on_trace_param
# CONFIGURAÇÕES DO KEYCLOAK:
keycloak:
  # Define a URL do serviço do keycloak.
  auth-server-url: http://localhost:4200/auth
  # Define o realm configurado para o keycloak.
  realm: Nava
  # Define o recurso configurado para o keycloak.
  resource: alma
  # Indica se o modo de autenticação Bearer está habilitado.
  bearer-only: true
  # Configuração de credenciais.
  cors: true
  # Configura parametro para captura do nome do usuário.
  principal-attribute: preferred_username

# CONFIGURAÇÕES DE LOG:
logging:
  # Define o nível do log para cada um dos pacotes.
  level:
    root: INFO

# CONFIGURAÇÕES DOS SERVIÇOS DO DATAFLOW-BACKEND
#management:
#  endpoints:
#    web:
#      base-path: /api/actuator
#      exposure:
#        include: info
#
#info:
#  app:
#    version: @project.version@
#    encoding: @project.build.sourceEncoding@
#    java:
#      version: @java.version@